### PR TITLE
Fix elfcopy test cases

### PR DESCRIPTION
**Pull request by markjdb**

### CODE REVIEW

**Comment by emaste** [comment]
Oh, rather I had your diff backwards I guess, so we're actually emitting `\0\0` now and c2d8f4b fixes that.

**Comment by markjdb** [comment]
Sure, though in the cases I modified here, it represents a savings of often less than 10 bytes.

**Comment by emaste** [comment]
> Sure, though in the cases I modified here, it represents a savings of often less than 10 bytes.

Good point, for shstrtab we're unlikely to have a significant benefit from suffix merging. There is a real benefit if we're able to merge shstrtab and strtab, when using -ffunction-sections.

In any case I opened https://sourceforge.net/p/elftoolchain/tickets/582/ to track the idea as perhaps something to look at after higher-priority items are dealt with.

**Comment by emaste** [comment]
Committed in b47abc4b09bfc0517eebcd9b6a20b00a4f7227b1 and 9c8cd2bb84b764e93b1e3bcaafdef22447c61624

CI is now green, https://github.com/emaste/elftoolchain/runs/473788324

**Pull request closed without merging**
